GITHUB_TOKEN = "s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"
GITHUB_USERNAME = "DSciALab"
GITHUB_REPO = "uaew"
GITHUB_FILEPATH = "perfil_atletas.json"
